name: Build Distributables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permissions for Gradle
        run: chmod +x gradlew

      - name: Build .msi
        run: ./gradlew packageMsi

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: notepad-windows-msi
          path: ./build/compose/binaries/main/msi/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permissions for Gradle
        run: chmod +x gradlew

      - name: Build .dmg
        run: ./gradlew packageDmg

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: notepad-macos-dmg
          path: ./build/compose/binaries/main/dmg/